<a href="https://colab.research.google.com/github/BigIceGolem/data-science-toolkit/blob/main/Tutorial_3_Amirun.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 2x2 Numpy array

import numpy as np
a = np.array ([[1,2,3]
              ,[4,5,6]])
print (a)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3x4 Numpy array of random numbers (float)

x = np.random.random((3,4))
print (x)

[[0.97657808 0.03046389 0.9381845  0.77999652]
 [0.25397843 0.39361681 0.73041186 0.52733957]
 [0.47774386 0.3687468  0.80214708 0.38072628]]


In [ ]:
# Numpy arrays of 1's & 0's

n1 = np.ones((2,2))
n0 = np.zeros((2,2))

print (n0)
print ("\n")
print (n1)

[[0. 0.]
 [0. 0.]]


[[1. 1.]
 [1. 1.]]


In [ ]:
# 6x3 Numpy array of random numbers


rand = np.random.random((6,3))
rand_T = rand.T

print (rand)
print("\n")
print (rand_T)


[[0.16297637 0.77130933 0.82303158]
 [0.35159997 0.10707237 0.97789712]
 [0.7384375  0.87799139 0.24224912]
 [0.57381185 0.20531546 0.56947578]
 [0.8551827  0.3292037  0.20635487]
 [0.77186108 0.45950036 0.08964825]]


[[0.16297637 0.35159997 0.7384375  0.57381185 0.8551827  0.77186108]
 [0.77130933 0.10707237 0.87799139 0.20531546 0.3292037  0.45950036]
 [0.82303158 0.97789712 0.24224912 0.56947578 0.20635487 0.08964825]]


In [ ]:
## Two random Numpy arrays and dot product


# Set a fixed seed for reproducible results
np.random.seed(42)

# 1. Define the dimensions
n = 3
p = 4
m = 2

print(f"Creating two random arrays:")
print(f"Array 1 (A) will have shape n x p = {n} x {p}")
print(f"Array 2 (B) will have shape p x m = {p} x {m}")
print("-" * 30)

# 2. Create the two random numpy arrays
# Using np.random.random() for floats between 0.0 and 1.0
A = np.random.random((n, p))
B = np.random.random((p, m))

print(f"Array A (shape {A.shape}):")
print(A)
print(f"\nArray B (shape {B.shape}):")
print(B)
print("-" * 30)

# 3. Compute the dot product
# The dot product of (n, p) and (p, m) results in an (n, m) matrix
dot_product = np.dot(A, B)

# An alternative modern syntax is:
# dot_product = A @ B

print(f"Dot Product (A . B) (shape {dot_product.shape}):")
print(dot_product)

Creating two random arrays:
Array 1 (A) will have shape n x p = 3 x 4
Array 2 (B) will have shape p x m = 4 x 2
------------------------------
Array A (shape (3, 4)):
[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]

Array B (shape (4, 2)):
[[0.83244264 0.21233911]
 [0.18182497 0.18340451]
 [0.30424224 0.52475643]
 [0.43194502 0.29122914]]
------------------------------
Dot Product (A . B) (shape (3, 2)):
[[0.96593779 0.81236013]
 [0.55005223 0.34447444]
 [1.05434944 0.55077179]]
